services:
  - type: web
    name: tokenhealth
    runtime: bun
    plan: free
    buildCommand: cd TokenHealth && bun install
    startCommand: cd TokenHealth && bun run start
    healthCheckPath: /
    envVars:
      - key: APP_PRIVATE_DATA
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: BASESCAN_API_KEY
        sync: false
      - key: ARBISCAN_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: POLYGONSCAN_API_KEY
        sync: false
      - key: SOLSCAN_API_KEY
        sync: false
      - key: PORT
        generateValue: true


